language: nodejs
node_js:
  - "8"
  - "9"

before_script:
  - npm i
  - npm run build

script:
  - npm run test
  - npm run lint

after_success:
  - npm pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "bulk-mail-cli-*.tgz"
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master